using ErrorOr;

namespace Yearly.Application.Common.Interfaces;

public interface IPhotoStorage
{
    /// <summary>
    /// Upload a photo to a storage
    /// </summary>
    /// <param name="imageData">The image data</param>
    /// <param name="name">The name of the photo</param>
    /// <param name="fileExtension">The file extension of the photo</param>
    /// <returns>A link to the photo resource. Use this same link to then delete the photo from the storage</returns>
    public Task<ErrorOr<string>> UploadPhotoAsync(Stream imageData, string name, string fileExtension);

    /// <param name="resourceLink">The link to the photo generated by <see cref="UploadPhotoAsync"/></param>
    public Task DeletePhotoAsync(string resourceLink);
}