//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yearly.MauiClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yearly.MauiClient.Resources.LocalizationResources", typeof(LocalizationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vypršela platnost loginu, prosím přihlašte se znovu.
        /// </summary>
        internal static string Authentication_CookieNotSigned {
            get {
                return ResourceManager.GetString("Authentication.CookieNotSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nedostatečná oprávnění.
        /// </summary>
        internal static string Authentication_InsufficientPermissions {
            get {
                return ResourceManager.GetString("Authentication.InsufficientPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Špatné jméno nebo heslo.
        /// </summary>
        internal static string Authentication_InvalidCredentials {
            get {
                return ResourceManager.GetString("Authentication.InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vypršela platnost loginu, prosím přihlašte se znovu.
        /// </summary>
        internal static string Authentication_SessionNotCached {
            get {
                return ResourceManager.GetString("Authentication.SessionNotCached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Něco se nepovedlo.
        /// </summary>
        internal static string Common_UnknownError {
            get {
                return ResourceManager.GetString("Common.UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Již zkonzumováno.
        /// </summary>
        internal static string Orders_AlreadyConsumed {
            get {
                return ResourceManager.GetString("Orders.AlreadyConsumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nemáte dostatek financí na kontě.
        /// </summary>
        internal static string Orders_InsufficientFunds {
            get {
                return ResourceManager.GetString("Orders.InsufficientFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Již je moc pozdě na zrušení objednávky.
        /// </summary>
        internal static string Orders_TooLateToCancelOrder {
            get {
                return ResourceManager.GetString("Orders.TooLateToCancelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Již je moc pozdě na objednání.
        /// </summary>
        internal static string Orders_TooLateToOrder {
            get {
                return ResourceManager.GetString("Orders.TooLateToOrder", resourceCulture);
            }
        }
    }
}
